import './globals.css'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'

const rubikFont = Rubik({ 
  weight:'500',
  subsets:['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubikFont.className}>{children}</body>
    </html>
  )
}
